/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: ca60713525c081b37a1c4f67927b145f)
interface __BaseEnv_Env {
	DB: D1Database;
	AI: Ai;
	SLACK_BOT_TOKEN: string;
	SLACK_SIGNING_SECRET: string;
	AdminAgent: DurableObjectNamespace<import("./src/server").AdminAgent>;
	OnboardingAgent: DurableObjectNamespace<import("./src/server").OnboardingAgent>;
	MESSAGE_WORKFLOW: Workflow<Parameters<import("./src/server").MessageWorkflow['run']>[0]['payload']>;
	LIFECYCLE_WORKFLOW: Workflow<Parameters<import("./src/server").LifecycleWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "AdminAgent" | "OnboardingAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SLACK_BOT_TOKEN" | "SLACK_SIGNING_SECRET">> {}
}
